// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tW5Yf9q_l05rcWfMqCu7Ic-ZoZNa1-0',
    appId: '1:30841251960:web:36c327b1962cfdbbc5e58d',
    messagingSenderId: '30841251960',
    projectId: 'salon-note',
    authDomain: 'salon-note.firebaseapp.com',
    storageBucket: 'salon-note.firebasestorage.app',
    measurementId: 'G-QK2GJHCPB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKSB6LoW6t4fbB3NIiar3U1pmoK--J6yA',
    appId: '1:30841251960:android:5e88d443b3c3fad5c5e58d',
    messagingSenderId: '30841251960',
    projectId: 'salon-note',
    storageBucket: 'salon-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFwIUZv6gAQiUylwaiV_m0D9Ps_hcxruo',
    appId: '1:30841251960:ios:ed2e444561242522c5e58d',
    messagingSenderId: '30841251960',
    projectId: 'salon-note',
    storageBucket: 'salon-note.firebasestorage.app',
    iosBundleId: 'com.kono.salonnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFwIUZv6gAQiUylwaiV_m0D9Ps_hcxruo',
    appId: '1:30841251960:ios:0650d32baeac79a6c5e58d',
    messagingSenderId: '30841251960',
    projectId: 'salon-note',
    storageBucket: 'salon-note.firebasestorage.app',
    iosBundleId: 'com.example.salonNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9tW5Yf9q_l05rcWfMqCu7Ic-ZoZNa1-0',
    appId: '1:30841251960:web:3a5ea4eadd595de4c5e58d',
    messagingSenderId: '30841251960',
    projectId: 'salon-note',
    authDomain: 'salon-note.firebaseapp.com',
    storageBucket: 'salon-note.firebasestorage.app',
    measurementId: 'G-QW7V8X1W44',
  );
}
